spring.application.name=first.project
server.port=8081

#OpenAPI Key :
spring.ai.model.chat=openai
spring.ai.openai.api.key={OPENAI_API_KEY}

logging.level.org.springframework.ai.chat.client.advisor=DEBUG

# Db conifg
spring.datasource.url=jdbc:mariadb://localhost:3308/springAi
spring.datasource.username=root
spring.datasource.password=root
spring.ai.vectorstore.mariadb.initialize-schema=true
spring.ai.vectorstore.mariadb.distance-type=COSINE
spring.ai.vectorstore.mariadb.dimensions=1536
#spring.ai.chat.memory.repository.jdbc.initialize-schema=always
